# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-18 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([]),
        ),
    ]
